Include dotenv in production image to prevent migration errors
```
 @asl/schema@11.1.9 migrate
> knex migrate:latest

Error in Knexfile: Error: Cannot find module 'dotenv'
Require stack:
- /app/packages/asl-schema/knexfile.js
- /app/node_modules/knex/lib/migrations/util/import-file.js
- /app/node_modules/knex/bin/cli.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/app/packages/asl-schema/knexfile.js:4:3)
    at Module._compile (node:internal/modules/cjs/loader:1706:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/packages/asl-schema/knexfile.js',
    '/app/node_modules/knex/lib/migrations/util/import-file.js',
    '/app/node_modules/knex/bin/cli.js'
  ]
}
```